version: '3.8'

services:

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - fiap-network

  postgres:
    image: postgres:15
    container_name: fiap-pedido-postgres
    restart: always
    environment:
      POSTGRES_DB: fiap-pedido-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fiap-network

  fiap-pedido-service:
    image: fiap-pedido-service:latest
    container_name: fiap-pedido-service
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fiap-pedido-service
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8079:8079"
    depends_on:
      - kafka
      - postgres
    networks:
      - fiap-network

volumes:
  kafka-data:
  pgdata:

networks:
  fiap-network: