version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fiap-pedido-postgres
    restart: always
    environment:
      POSTGRES_DB: fiap-pedido-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fiap-network

  fiap-cliente-service:
    image: fiap-pedido-service:latest
    container_name: fiap-pedido-service
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: fiap-pedido-service
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8079:8079"
    depends_on:
      - postgres
    networks:
      - fiap-network

volumes:
  pgdata:

networks:
  fiap-network: